site_name: S(i)PIN Radiation Detector
site_url: https://spin-rd.com/docs
docs_dir: content
site_dir: build
repo_url: https://github.com/lewis206/spin-rd
repo_name: lewis206/spin-rd
edit_uri: ""
theme:
  name: material
  font:
    text: DM Sans

extra_css:
  - https://cdn.jsdelivr.net/npm/@splidejs/splide@latest/dist/css/splide.min.css

extra_javascript:
  - https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js
  - https://cdn.jsdelivr.net/npm/@splidejs/splide@latest/dist/js/splide.min.js
  - javascripts/slideshow.js

nav:
  - "Tutorials":
      - "Particle Accelerators and Detectors": "tutorials/first_tutorial.md"
      - "Required Parts": "tutorials/second_tutorial.md"
  - "Carousel Test": "slideshow.md"
