site_name: S(i)PIN Radiation Detector
site_url: https://spin-rd.com/docs
docs_dir: content
site_dir: build
repo_url: https://github.com/lewis206/spin-rd
repo_name: lewis206/spin-rd
edit_uri: ""
theme:
  name: material
  font:
    text: DM Sans

nav:
  - "Tutorials":
      - "Particle Accelerators and Detectors": "tutorials/first_tutorial.md"
      - "Required Parts": "tutorials/second_tutorial.md"
