site_name: S(i)PIN Radiation Detector
site_url: https://spin-rd.com/docs
docs_dir: content
site_dir: build
repo_url: https://github.com/lewis206/spin-rd
repo_name: lewis206/spin-rd
edit_uri: ""
theme:
  name: material
  font:
    text: DM Sans

nav:
  - Home: "index.md"
  - "Tutorials":
      - "First Tutorial": "tutorials/first_tutorial.md"
      - "Second Tutorial": "tutorials/second_tutorial.md"
  - "Plots": "plots.ipynb"
  - About: "about.md"

plugins:
  - mknotebooks

extra_css:
  - stylesheets/interactive.css

extra_javascript:
  - javascripts/extra.js
